version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=main:app # ✅ Properly reference app instance
      - FLASK_ENV=development
    command: 'python main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.42
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: vatsan1993
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
