version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=main.py
    # command: /bin/sh -c "flask run --host=0.0.0.0"
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.42
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: vatsan1993
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 33067:3306 # Expose MySQL on port 33066 so that local MySQL port is not blocked

volumes:
  dbdata:
